In [3]:
import json

In [12]:
policies_data=None
try:
    with open('filtered_policies.json', 'r', encoding='utf-8') as f:
        policies_data = json.load(f)
except Exception:
    policies_data=''

In [19]:
import json

# Load the JSON file
file_path = "filtered_policies.json"  # Replace with the actual path if different
with open(file_path, "r", encoding="utf-8") as file:
    data = json.load(file)

# Extract and print the "거주지 및 소득" information
for policy in data:
    policy_title = policy.get("Policy Title", "Unknown Policy")
    details = policy.get("Details", [])
    for detail in details:
        if detail.get("Title") == "거주지 및 소득":
            residence_income = detail.get("Content", "No details available")
            print(f"{residence_income}")



❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
-
○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)
※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
상주시 청년(만 19세 ~ 39세 이하)이고, 지역 정착 창업사업 참여자
○ 

- 거주지 및 소득
❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)
※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
상주시 청년(만 19세 ~ 39세 이하)이고, 지역 정착 창업사업 참여자
○ (원가구) 청년독립가구 + 1촌이내 직계혈족(부·모)소지에 거주하는 그 외「민법」상 가족소득 50% 이상으로 생계를 달리한다고 시·군·구청장이 인정하는 경우 등은 원가구 소득 미고려
· 지원대상: 신청일 기준, 남편 또는 아내가 1년 이상 의성군에 주소를 두고 거주하며, 혼인신고일 이후 부부가 함께 의성군에 주민등록을 둔 결혼 1년 이하 무주택 신혼부부
- 법령에서 정한 정기점검 기간이 이미 경과하였거나 점검유예한 주택 
※ 보장기관이 인정하는 경우 예외 가능주민등록상 시·군을 달리하는 경우 인정미만의 미혼자녀
 ○ 소득이 없을 경우 국세청 사실증명원 등 소득이 없다는 증빙서류 필요0% 이하
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
 * 19~34세 : 국토부(전국) 청년월세 한시특별 지원 / 35~39세 : 인천형 청년월세 지원의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인(이혼) ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
*입주자 모집공고 확인
공고문 필히 참고
추후 공고문 참고
○ 이주주택 임대차 계약서 상 임차인은 본 사업 신청인과 동일인일 것민등록을 두고 실제 거주하는 자
※ [필독] 기본적으로 전년도 소득증빙자료로 선정여부를 결정하나, 금년도 은행 대출시에도 연령·소득요건은 반드시 유지해야 함
○ 지원대상 : 주거급여 수급가구 내 만 19세 이상 30세 미만 미혼자녀
○ 대 상 : 18세 이상 39세 이하 무주택 청년노동자
○ 지원대상 : 주거급여 수급자의 19세 ~ 30세 미만의 미혼자녀
○ 대 상 : 동구 거주 또는 생활 청년(18세 ~ 39세)
○ 지원대상 : 중구에 거주·생활 또는 전입예정인 18세 ~ 34세 이하 청년
❍(주택소유여부) 가족관계증명서의 본인 및 배우자 소유 주택이 없을 것지원 불가인)31. 출생자)
※ 아파트, 자가 거주자, 기 지원자 제외
② 2022~2023년 청년 1인 가구 생활안전키트를 지원받지 아니한 사람
○ 대상 : 19세 이상 39세 이하 무주택 미혼 청년19세이상 39세이하)
④ (제외) 주거급여수급자, 울주군 신혼부부 주거지원 사업 대상자와 중복 지급불가전세임대 거주하고 있는 가구①~④요건 모두 만족) 
- 부부합산소득이 기준중위소득 200%(7,365천원) 이하인 가구(2인 기준) 중인 신혼부부
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
○ 주택 : 임대차계약 보증금이 3억원 이하인 주민등록 주소지와 일치하는 주거용 주택증금반환보증에 가입된 경우 신청 가능 (2024. 6. 30. 이전 신청자에 한함.)
□ 신청대상 : 입주자 모집 공고일(2024. 5. 30.) 현재 만19세 이상 만39세 이하의 청년으로 전년도 도시근로자 월평균소득의 120% (4,179,557원)이하인 자
지역기준: 제주도, 제주시, 서귀포시
  ○ 19세∼39세(무주택 저소득 청년)·신혼부부·고령자 등
*보증기관: 주택도시보증공사(HUG), 한국주택금융공사(HF), 서울보증보험(SGI)시 거주 무주택자(본인 및 배우자 모두 무주택자) 
□ 19-34세 부모님과 별도로 거주하는 무주택 청년
※ 제외대상 : 아파트 및 오피스텔 거주자, 자가 소유자자모자)가정
▶ 아동복지시설 :  아동양육시설, 공동생활가정, 가정위탁택자로서 아동복지시설을 만기 또는 중도 퇴소(예정)한 29세 이하 청년
※ 2024년 3월 1일 이후 접수자부터 아래의 신청자격 기준 적용및 자산 기준을 충족하는 자
* 사실혼인 경우 사실혼관계증명 필요(제3자와 혼인관계 없으며, 1년 이상 동거해야 함. 주민등록등본 추가 제출)50% 이상으로 부모와 생계를 달리하는 청년
  ※ 45세 이하군에 주민등록이 되어있는 18세 ~ 45세 이하의 세대주 청년 또는 혼인신고일 기준 5년 미만인 신혼부부
  ※ 원가구 : 청년가구+1촌이내 직계혈족(부모)소지 거주중 민법상 가족이하
□ 예산군으로 귀농하고자 하는 20~40대 예비귀농인
□ 다른 시‧군‧구에서 전입일을 기준으로 1년이상 주소를 두고 있다가 군 내에 전입한 자
□ 부여군 주민등록을 두고 거주하거나 거주 예정인 무주택 청년
□ 대상자 : ⌜청년기본법⌟상 청년(만 19~34세 이하)으로 부모님과 별도 거주하는 무주택자
(※ 자세한 사항 공고문 참고)있지 않거나 주거기본법 제17조 최저주거기준의 주거면적에 미달하는 주택을 소유하고 있는 자를 말함
ㅇ기혼자:부부및자녀등포함가구원수계산(최소2인)단독세대를구성하고(예정포함)미혼인경우1인기준적용형제·자매는가구원수에서제외),부모합산소득으로판별(본인소득제외)
-건강보험증(사본) *건강보험 자격확인(통보)서 대체 가능
 ※ 18~39세 또는 직장을 두거나, 활동·생활하고자 하는 무주택 청년
○ (원가구) 기준중위소득 100%이하&(청년독립가구) 기준 중위소득 60%이하무주택 청년(청약저축 가입자)
❍ 지원자격 : 청년가구 소득 기준 중위소득 60% 이하, 원가구 소득 기준 중위소득 100% 이하
지역기준 : 제주도, 제주시, 서귀포시
서울시 거주 또는 거주예정인 1인가구
-
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
 ※ 거주하는 본인 또는 시민 자녀
-
□ 부모와 별도 거주하는 무주택 저소득 청년
□ 가구소득인정액이 기준중위소득 180%이하인 자전원 무주택자 주택구입자금 또는 전월세보증금 대출 후 1개월 이내 전입 예정자
  - 건축물대장상 주택이 아닌 곳과 불법건축물, 다중 주택, 공공임대주택은 지원 불가월세 70만원 이하의 전월세계약하인 자
   - 신혼부부 : 신혼부부 및 자녀 합산 자산 기준 3억 4,500만원 이하수별 가구당 월평균 소득 120%이하(2인가구:6,498,854원 / 3인가구:8.638.379원)
기타 자세한 모집요강 및 세부 내용은 첨부된 공고문 참고
□ 월세가 70만원이 초과되더라도 보증금의 월세환산액(연 5.5%)과 월세액의 합계액이 90만원 이하의 경우는 지원
※ (신청일 기준) 임대차 계약을 맺은 건물(진안군 소재)에 주민등록이 등재되어 있어야 함.세(70만원 이하) 또는 전세(임차보증금 1억 5천만원 이하이면서 대출금 유) 건물
□ 미혼청년(만18 ∼ 39세) 혼인 7년이내/혼인신고일 기준)
    - 기준중위소득 180퍼센트 이하인 본인 (배우자,자녀포함) 소유의 주택이 없는 다자녀가구
※ 이사비 지원액 예산 초과 시, 접수 완료 순으로 선착순 지급를 요청할 수 있음건강보험료 소득판정’기준표상 기준 중위소득 180% 이하
연수구 청년 누구나
□ 소득기준 : (원가구) 기준 중위소득 100% 이하 & (청년독립가구) 기준 중위소득 60% 이하
주거 자금(구입, 전세) 목적으로 금융권 대출을 실행한 충주시 거주 혼인 7년 이내 청년 신혼부부 - 지원대상 세부 자격 공고문 확인
본인 또는 친권자(후견자)의 주소가 충청북도인 자 - (서/동서울관) 수도권 지역 대학의 신입생 또는 재학생 - (청 주 관) 도내 대학(원)의 신입생 또는 재학생
도내 거주 19세 ~ 34세 이하 부모님과 별도거주 무주택 청년 (청약통장 가입 필수) - 소득요건 : 원가구 중위소득 100%이하+청년가구 중위소득 60%이하
-
퇴소했거나 재원중이거나 보호가 종료된 아동(만18세~34세) 1,000명
 (일반형) 부부합산 연소득 5천만원 이하자 중 우대형에 해당하지 아니한 자로 인정되는 자 포함)인 자주(세대주로 인정되는자 포함)인 자불가능중 소득 3분위 전체가구 평균값 이하(십만원 단위에서 반올림)인 자


In [27]:
import json
from dataclasses import dataclass
from typing import List, Optional, Dict, Any
import re
from datetime import datetime, date

debug=True

@dataclass
class MonetaryValue:
    amount: int  # 원 단위
    original_text: str

@dataclass
class Period:
    start_date: Optional[date]
    end_date: Optional[date]
    original_text: str

@dataclass
class IncomeRequirement:
    type: str  # "중위소득", "도시근로자" 등
    percentage: Optional[float]  # 비율 (예: 120.0)
    amount: Optional[MonetaryValue]  # 구체적 금액이 명시된 경우
    household_type: str  # "원가구", "청년가구", "부부합산" 등

@dataclass
class PolicyCriteria:
    age_min: Optional[int]
    age_max: Optional[int]
    region: List[str]
    marriage_required: Optional[bool]
    residence_status: Dict[str, Any]
    income_requirements: List[IncomeRequirement]
    asset_limit: Optional[MonetaryValue]
    application_period: Optional[Period]
    support_amount: Optional[MonetaryValue]
    requirements: Dict[str, bool]
    validation_errors: List[str]
    income_assets: Dict[str, Any]
    status: Dict[str, bool]

    def __str__(self):
        return (
            f"PolicyCriteria(\n"
            f"  age_min: {self.age_min},\n"
            f"  age_max: {self.age_max},\n"
            f"  region: {', '.join(self.region) if self.region else 'None'},\n"
            f"  marriage_required: {self.marriage_required},\n"
            f"  residence_status: {self.residence_status},\n"
            f"  income_requirements: {self.income_requirements},\n"
            f"  asset_limit: {self.asset_limit},\n"
            f"  application_period: {self.application_period},\n"
            f"  support_amount: {self.support_amount},\n"
            f"  requirements: {self.requirements},\n"
            f"  validation_errors: {self.validation_errors},\n"
            f"  income_assets: {self.income_assets},\n"
            f"  status: {self.status}\n"
            f")"
        )

class KoreanNumberConverter:
    def __init__(self):
        self.korean_numbers = {
            '일': 1, '이': 2, '삼': 3, '사': 4, '오': 5,
            '육': 6, '칠': 7, '팔': 8, '구': 9,
            '일': 1, '둘': 2, '셋': 3, '넷': 4, '다섯': 5,
            '여섯': 6, '일곱': 7, '여덟': 8, '아홉': 9,
            '십': 10, '백': 100, '천': 1000, '만': 10000,
            '억': 100000000
        }
        
    def convert_to_number(self, korean_text: str) -> Optional[int]:
        try:
            # 숫자로 된 경우 바로 변환
            return int(korean_text)
        except ValueError:
            result = 0
            temp = 0
            unit = 1
            
            for char in korean_text:
                if char in self.korean_numbers:
                    number = self.korean_numbers[char]
                    if number >= 10000:
                        temp = temp if temp > 0 else 1
                        result += (temp * number)
                        temp = 0
                    elif number >= 10:
                        temp = temp if temp > 0 else 1
                        temp *= number
                    else:
                        temp = number
            
            return result + temp

class MonetaryParser:
    def __init__(self):
        self.number_converter = KoreanNumberConverter()
        self.amount_patterns = [
            r'(\d+|\w+)(?:백만|천만|만|억)원',
            r'(\d+|\w+)원',
            r'금?\s*(\d+|\w+)(?:백만|천만|만|억)\s*원?'
        ]
        
    def parse_amount(self, text: str) -> Optional[MonetaryValue]:
        for pattern in self.amount_patterns:
            match = re.search(pattern, text)
            if match:
                amount_text = match.group(1)
                unit_text = match.group(0)
                
                base_amount = self.number_converter.convert_to_number(amount_text)
                if not base_amount:
                    continue
                    
                # 단위 처리
                if '억' in unit_text:
                    amount = base_amount * 100000000
                elif '천만' in unit_text:
                    amount = base_amount * 10000000
                elif '백만' in unit_text:
                    amount = base_amount * 1000000
                elif '만' in unit_text:
                    amount = base_amount * 10000
                else:
                    amount = base_amount
                    
                return MonetaryValue(amount=amount, original_text=match.group(0))
        
        return None

class DateParser:
    def __init__(self):
        self.date_patterns = [
            r'(\d{4})[./\s-](\d{1,2})[./\s-](\d{1,2})',  # 2024-01-01
            r'(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일',    # 2024년 1월 1일
            r'(\d{2})\.(\d{1,2})\.(\d{1,2})',           # 24.1.1
        ]
        self.period_patterns = [
            r'(?:신청|접수|모집)기간\s*:?\s*([^~]*)[~까지]([^\n]*)',
            r'(\d{4}[./년\s]\d{1,2}[./월\s]\d{1,2}[일]?\s*)[~부터\s]+(\d{4}[./년\s]\d{1,2}[./월\s]\d{1,2}[일]?)',
        ]
        
    def parse_date(self, text: str) -> Optional[date]:
        for pattern in self.date_patterns:
            match = re.search(pattern, text)
            if match:
                year = int(match.group(1))
                month = int(match.group(2))
                day = int(match.group(3))
                
                # 2자리 연도 처리
                if year < 100:
                    year += 2000
                    
                try:
                    return date(year, month, day)
                except ValueError:
                    continue
        
        return None
        
    def parse_period(self, text: str) -> Optional[Period]:
        for pattern in self.period_patterns:
            match = re.search(pattern, text)
            if match:
                start_text = match.group(1)
                end_text = match.group(2)
                
                start_date = self.parse_date(start_text)
                end_date = self.parse_date(end_text)
                
                return Period(
                    start_date=start_date,
                    end_date=end_date,
                    original_text=match.group(0)
                )
        
        return None

class IncomeParser:
    def __init__(self):
        self.patterns = {
            "중위소득": r'중위소득\s*(\d+)%\s*(?:이하|미만)?',
            "도시근로자": r'도시근로자\s*(?:월평균\s*)?소득\s*(\d+)%\s*(?:이하|미만)?'
        }
        
    def parse_income_requirements(self, text: str) -> List[IncomeRequirement]:
        requirements = []
        
        for income_type, pattern in self.patterns.items():
            matches = re.finditer(pattern, text)
            for match in matches:
                percentage = float(match.group(1))
                
                # 가구 유형 확인
                household_type = "일반"
                if "원가구" in text:
                    household_type = "원가구"
                elif "부부합산" in text:
                    household_type = "부부합산"
                elif "청년" in text:
                    household_type = "청년가구"
                
                requirements.append(IncomeRequirement(
                    type=income_type,
                    percentage=percentage,
                    amount=None,  # 구체적 금액은 별도 처리 필요
                    household_type=household_type
                ))
                
        return requirements



class RequirementsValidator:
    def validate_requirements(self, req: PolicyCriteria) -> List[str]:
        errors = []
        
        # 나이 검증
        if req.age_min is not None and req.age_max is not None:
            if req.age_min > req.age_max:
                errors.append(f"최소 나이({req.age_min})가 최대 나이({req.age_max})보다 큽니다")
                
        # 날짜 검증
        if req.application_period:
            if (req.application_period.start_date and 
                req.application_period.end_date and 
                req.application_period.start_date > req.application_period.end_date):
                errors.append("시작일이 종료일보다 늦습니다")
                
        # 필수 항목 검증
        if not req.region and not req.requirements.get("전국대상", False):
            errors.append("지역 정보가 없습니다")
            
        return errors


class RegionManager:
    def __init__(self):
        self.region_dict = {
            
"경상북도": [
            "포항시 남구", "포항시 북구", "경주시", "김천시", "안동시", "구미시", "영주시", 
            "영천시", "상주시", "문경시", "경산시", "군위군", "의성군", "청송군", "영양군",
            "영덕군", "청도군", "고령군", "성주군", "칠곡군", "예천군", "봉화군", "울진군",
            "울릉군"
        ],
        "대전광역시": ["동구", "중구", "서구", "유성구", "대덕구"],
        "서울특별시": [
            "종로구", "중구", "용산구", "성동구", "광진구", "동대문구", "중랑구", "성북구",
            "강북구", "도봉구", "노원구", "은평구", "서대문구", "마포구", "양천구", "강서구",
            "구로구", "금천구", "영등포구", "동작구", "관악구", "서초구", "강남구", "송파구",
            "강동구"
        ],
        "부산광역시": [
            "중구", "서구", "동구", "영도구", "부산진구", "동래구", "남구", "북구",
            "해운대구", "사하구", "금정구", "강서구", "연제구", "수영구", "사상구",
            "기장군"
        ],
        "인천광역시": [
            "중구", "동구", "미추홀구", "연수구", "남동구", "부평구", "계양구", "서구",
            "강화군", "옹진군"
        ],
        "광주광역시": ["동구", "서구", "남구", "북구", "광산구"],
        "대구광역시": [
            "중구", "동구", "서구", "남구", "북구", "수성구", "달서구", "달성군"
        ],
        "울산광역시": ["중구", "남구", "동구", "북구", "울주군"],
        "세종특별자치시": ["세종시"],
        "제주특별자치도": ["제주시", "서귀포시"],
        "기타": ["기타"]
        }
        
        # Create reverse lookup dictionary
        self.district_to_region = {}
        for region, districts in self.region_dict.items():
            for district in districts:
                self.district_to_region[district] = region
                # Also add the district name without the 시/군/구
                district_name = re.sub(r'시|군|구$', '', district)
                self.district_to_region[district_name] = region

    def normalize_region(self, region_text: str) -> List[str]:
        """주어진 텍스트에서 지역 정보를 정규화하여 반환"""
        if not region_text:
            return []
            
        found_regions = []
        
        # 광역시/도 직접 매칭
        for region in self.region_dict.keys():
            if region in region_text:
                found_regions.append(region)
                
        # 구/군 매칭
        for district in self.district_to_region.keys():
            if district in region_text:
                parent_region = self.district_to_region[district]
                if parent_region not in found_regions:
                    found_regions.append(parent_region)
                found_regions.append(district)
                
        return found_regions


class ExtendedRequirementsParser():
    def __init__(self):
        self.age_patterns = [
            r'(?:만\s*)?(\d+)\s*[~∼-]\s*(?:만\s*)?(\d+)\s*세?',  # 19-39세, 만 19~39세
            r'(?:만\s*)?(\d+)\s*세?\s*이[상하]',  # 19세 이상, 만 19세 이상
            r'청년\(\s*(?:만\s*)?(\d+)\s*[~∼-]\s*(?:만\s*)?(\d+)\s*세?\s*\)'  # 청년(19-39세)
        ]
        
        self.region_patterns = [
            r'([가-힣]+[시군구도])[에서\s]',  # ~시/군/구/도에서
            r'([가-힣]+[시군구도])[ 거주]',  # ~시/군/구/도 거주
            r'([가-힣]+[시군구도])\s',  # ~시/군/구/도
            r'지역기준[:\s]*([가-힣,\s]+)', 
        ]
        
        self.marriage_patterns = [
            r'신혼부부',
            r'혼인',
            r'결혼',
            r'미혼'
        ]
        self.region_manager = RegionManager()  # 이전 코드의 RegionManager 사용
        self.monetary_parser = MonetaryParser()
        self.date_parser = DateParser()
        self.income_parser = IncomeParser()
        self.validator = RequirementsValidator()
    def _get_detail(self, item: Dict, title: str) -> str:
        for detail in item["Details"]:
            if detail["Title"] == title:
                return detail["Content"]
        return ""


    def extract_age(self, text: str) -> tuple[Optional[int], Optional[int]]:
        for pattern in self.age_patterns:
            match = re.search(pattern, text)
            if match:
                if len(match.groups()) == 2:
                    return int(match.group(1)), int(match.group(2))
                else:
                    age = int(match.group(1))
                    if '이상' in text:
                        return age, None
                    elif '이하' in text:
                        return None, age
                    elif '대' in text:
                        return age, age + 9
        return None, None

    def extract_regions(self, text: str) -> List[str]:
        found_regions = set()
        
        # 패턴 매칭으로 지역 추출
        for pattern in self.region_patterns:
            matches = re.finditer(pattern, text)
            for match in matches:
                region_text = match.group(1).strip()
                # 쉼표로 구분된 여러 지역 처리
                for region in region_text.split(','):
                    region = region.strip()
                    normalized_regions = self.region_manager.normalize_region(region)
                    found_regions.update(normalized_regions)
        
        return list(found_regions)

    def extract_marriage_status(self, text: str) -> Optional[bool]:
        if '미혼' in text:
            return False
        elif any(keyword in text for keyword in ['신혼부부', '혼인', '결혼']):
            return True
        return None

    def extract_residence_status(self, text: str) -> Dict[str, Any]:
        status = {
            "무주택": False,
            "전월세": False,
            "임차보증금_제한": None,
            "월세_제한": None
        }
        
        if '무주택' in text:
            status["무주택"] = True
        
        if '전월세' in text or '월세' in text:
            status["전월세"] = True
            
        # 임차보증금 제한 추출
        match = re.search(r'임차보증금\s*(\d+)[만천억]*원', text)
        if match:
            amount = self._convert_korean_amount(match.group(1))
            status["임차보증금_제한"] = amount
            
        # 월세 제한 추출
        match = re.search(r'월세\s*(\d+)[만천]*원', text)
        if match:
            amount = self._convert_korean_amount(match.group(1))
            status["월세_제한"] = amount
            
        return status

    def extract_income_assets(self, text: str) -> Dict[str, Any]:
        income_assets = {
            "소득_기준": None,
            "재산_기준": None,
            "기타_소득조건": []
        }
        
        # 중위소득 기준 추출
        matches = re.finditer(r'중위소득\s*(\d+)%', text)
        if matches:
            income_assets["소득_기준"] = [f"중위소득 {m.group(1)}%" for m in matches]
            
        # 재산 기준 추출
        match = re.search(r'재산\s*(\d+)(?:백만|천만|억)원', text)
        if match:
            income_assets["재산_기준"] = self._convert_korean_amount(match.group(1))
            
        return income_assets

    def _convert_korean_amount(self, amount_str: str) -> int:
        # 숫자 변환 로직 구현
        try:
            return int(amount_str)
        except ValueError:
            return 0

    def extract_status(self, text: str) -> Dict[str, bool]:
        status = {
            "대학생": False,
            "직장인": False,
            "창업자": False,
            "귀농인": False
        }
        
        if '대학생' in text or '재학생' in text:
            status["대학생"] = True
        if '직장' in text or '근로자' in text:
            status["직장인"] = True
        if '창업' in text:
            status["창업자"] = True
        if '귀농' in text:
            status["귀농인"] = True
            
        return status

    def extract_requirements(self, text: str) -> Dict[str, bool]:
        requirements = {
            "청약통장": False,
            "전입신고": False,
            "부모별도거주": False
        }
        
        if '청약통장' in text:
            requirements["청약통장"] = True
        if '전입신고' in text:
            requirements["전입신고"] = True
        if '부모' in text and ('별도' in text or '따로' in text):
            requirements["부모별도거주"] = True
            
        return requirements

    
    def parse(self, item: Dict) -> PolicyCriteria:
        # 기본 정보 추출 (이전 코드의 기능 활용)
        text = self._get_detail(item, "거주지 및 소득")
        age_min, age_max = self.extract_age(text)
        regions = self.extract_regions(text)
        marriage_required = self.extract_marriage_status(text)
        residence_status = self.extract_residence_status(text)
        income_assets = self.extract_income_assets(text)
        status = self.extract_status(text)
        requirementss = self.extract_requirements(text)
        
        # 기타 조건은 향후 확장성을 위해 리스트로 유지
        # other = []
        
        # 새로운 정보 추출
        income_requirements = self.income_parser.parse_income_requirements(text)
        application_period = self.date_parser.parse_period(text)
        
        # 지원금액 추출
        support_amount = None
        if "지원금액" in text or "지원한도" in text:
            amount_text = text[text.find("지원금액"):]
            support_amount = self.monetary_parser.parse_amount(amount_text)
        
        # 요구사항 생성
        requirements = PolicyCriteria(
            age_min=age_min,
            age_max=age_max,
            region=regions,
            marriage_required=marriage_required,
            residence_status=residence_status,  # 이전 코드의 기능 활용
            income_requirements=income_requirements,
            asset_limit=None,  # 자산 제한 추출 필요
            application_period=application_period,
            support_amount=support_amount,
            requirements=requirementss,  # 이전 코드의 기능 활용
            validation_errors=[],
            income_assets=income_assets,
            status=status,
        )
        
        if debug:
            print(text)
            print(requirements)
            print('-'*50)

        # 검증 수행
        requirements.validation_errors = self.validator.validate_requirements(requirements)
        
        return requirements


@dataclass
class Policy:
    policy_id: str
    title: str
    criteria: PolicyCriteria
    description: str
    details: Dict[str, str]

class PolicyFilter:
    def __init__(self, json_data: str):
        self.policies = self._parse_policies(json_data)
    
    def _parse_policies(self, json_data: str) -> List[Policy]:
        data = json.loads(json_data)
        policies = []
        parser = ExtendedRequirementsParser()
        
        for item in data:
            criteria=parser.parse(item)
            
            policy = Policy(
                policy_id=self._get_detail(item, "정책 번호"),
                title=item["Policy Title"],
                criteria=criteria,
                description=item["Description"],
                details={detail["Title"]: detail["Content"] for detail in item["Details"]}
            )
            policies.append(policy)
            
        
        return policies
    
    def _get_detail(self, item: Dict, title: str) -> str:
        for detail in item["Details"]:
            if detail["Title"] == title:
                return detail["Content"]
        return ""
    
    
    def filter_policies(self, 
                       age: int = None,
                       region: str = None,
                       income_percent: float = None,
                       monthly_rent: int = None,
                       deposit: int = None,
                       is_married: bool = None) -> List[Policy]:
        """
        주어진 조건에 맞는 정책들을 필터링하여 반환합니다.
        
        Args:
            age: 나이
            region: 지역
            income_percent: 중위소득 대비 비율 (%)
            monthly_rent: 월세 금액 (만원)
            deposit: 보증금 금액 (만원)
            is_married: 혼인 여부
        """
        eligible_policies = []
        
        for policy in self.policies:
            criteria = policy.criteria
            
            # 각 조건 검사
            if age is not None and criteria.age_min is not None and criteria.age_max is not None:
                if not (criteria.age_min <= age <= criteria.age_max):
                    continue
                    
            # if region is not None and criteria.region is not None:
            #     if criteria.region != region:
            #         continue
                    
            # if income_percent is not None and criteria.income is not None:
            #     if income_percent > criteria.income_limit:
            #         continue
                    
            # if monthly_rent is not None and criteria.monthly_rent_limit is not None:
            #     if monthly_rent > criteria.monthly_rent_limit:
            #         continue
                    
            # if deposit is not None and criteria.deposit_limit is not None:
            #     if deposit > criteria.deposit_limit:
            #         continue
                    
            # if is_married is not None and criteria.marriage_required is not None:
            #     if criteria.marriage_required and not is_married:
            #         continue
            
            eligible_policies.append(policy)
            
        return eligible_policies

def main():
    # 사용 예시
    with open('filtered_policies.json', 'r', encoding='utf-8') as f:
        json_data = f.read()
    
    policy_filter = PolicyFilter(json_data)
    
    # 예시: 28세, 경북 거주, 중위소득 100%, 월세 50만원, 보증금 3000만원, 기혼
    eligible_policies = policy_filter.filter_policies(
        age=28,
        region="경북",
        income_percent=100,
        monthly_rent=50,
        deposit=3000,
        is_married=True
    )

    print(len(eligible_policies))
    
    for policy in eligible_policies:
        print(f"\n정책명: {policy.title}")
        print(f"정책 ID: {policy.policy_id}")
        print(f"지원 내용: {policy.details.get('거주지 및 소득', '')}")

if __name__ == "__main__":
    main()

❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
PolicyCriteria(
  age_min: None,
  age_max: None,
  region: None,
  marriage_required: None,
  residence_status: {'무주택': False, '전월세': False, '임차보증금_제한': None, '월세_제한': None},
  income_requirements: [],
  asset_limit: None,
  application_period: None,
  support_amount: None,
  requirements: {'청약통장': False, '전입신고': False, '부모별도거주': False},
  validation_errors: [],
  income_assets: {'소득_기준': [], '재산_기준': None, '기타_소득조건': []},
  status: {'대학생': False, '직장인': False, '창업자': False, '귀농인': False}
)
--------------------------------------------------
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
PolicyCriteria(
  age_min: 19,
  age_max: None,
  region: 북, 경상북도, 울산광역시,
  marriage_required: True,
  residence_status: {'무주택': True, '전월세': True, '임차보증금_제한': 5, '월세_제한': 80},
  income_requirements: [],
  asset_limit: None,
  application_p

# Error case
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
최소 나이 : None, 최대 나이 : None, 소득 제한 : None, 보증금 제한 : 5

○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)
최소 나이 : 19, 최대 나이 : 39, 지역 : 인천,             소득 제한 : 60.0, 월세 제한 : 70,                 보증금 제한 : 5, 결혼 유무 : True,                 부가 조건: {}

※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
최소 나이 : 19, 최대 나이 : 39, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}


상주시 청년(만 19세 ~ 39세 이하)이고, 지역 정착 창업사업 참여자
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


○ (원가구) 청년독립가구 + 1촌이내 직계혈족(부·모)소지에 거주하는 그 외「민법」상 가족소득 50% 이상으로 생계를 달리한다고 시·군·구청장이 인정하는 경우 등은 원가구 소득 미고려
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : 60.0, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}



지원대상: 신청일 기준, 남편 또는 아내가 1년 이상 의성군에 주소를 두고 거주하며, 혼인신고일 이후 부부가 함께 의성군에 주민등록을 둔 결혼 1년 이하 무주택 신혼부부
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}


 ○ 소득이 없을 경우 국세청 사실증명원 등 소득이 없다는 증빙서류 필요0% 이하
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : 180.0, 월세 제한 : None,                 보증금 제한 : 2, 결혼 유무 : False,                 부가 조건: {}



○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
최소 나이 : 19, 최대 나이 : 39, 지역 : 인천,             소득 제한 : 60.0, 월세 제한 : 70,                 보증금 제한 : 5, 결혼 유무 : True,                 부가 조건: {}

* 19~34세 : 국토부(전국) 청년월세 한시특별 지원 / 35~39세 : 인천형 청년월세 지원의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인(이혼) ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
최소 나이 : 19, 최대 나이 : 39, 지역 : 인천,             소득 제한 : 60.0, 월세 제한 : 70,                 보증금 제한 : 5, 결혼 유무 : True,                 부가 조건: {}


※ [필독] 기본적으로 전년도 소득증빙자료로 선정여부를 결정하나, 금년도 은행 대출시에도 연령·소득요건은 반드시 유지해야 함
최소 나이 : 19, 최대 나이 : 39, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}



○ 지원대상 : 주거급여 수급가구 내 만 19세 이상 30세 미만 미혼자녀
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


○ 대 상 : 18세 이상 39세 이하 무주택 청년노동자
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


○ 지원대상 : 주거급여 수급자의 19세 ~ 30세 미만의 미혼자녀
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


○ 대 상 : 동구 거주 또는 생활 청년(18세 ~ 39세)
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}



○ 지원대상 : 중구에 거주·생활 또는 전입예정인 18세 ~ 34세 이하 청년
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}



❍(주택소유여부) 가족관계증명서의 본인 및 배우자 소유 주택이 없을 것지원 불가인)31. 출생자)
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : 180.0, 월세 제한 : 60,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


※ 아파트, 자가 거주자, 기 지원자 제외
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


② 2022~2023년 청년 1인 가구 생활안전키트를 지원받지 아니한 사람
최소 나이 : 19, 최대 나이 : 45, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


  ○ 19세∼39세(무주택 저소득 청년)·신혼부부·고령자 등
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}


*보증기관: 주택도시보증공사(HUG), 한국주택금융공사(HF), 서울보증보험(SGI)시 거주 무주택자(본인 및 배우자 모두 무주택자) 
최소 나이 : None, 최대 나이 : None, 지역 : 서울,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}



□ 19-34세 부모님과 별도로 거주하는 무주택 청년
최소 나이 : 19, 최대 나이 : 34, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


▶ 아동복지시설 :  아동양육시설, 공동생활가정, 가정위탁택자로서 아동복지시설을 만기 또는 중도 퇴소(예정)한 29세 이하 청년
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}



* 사실혼인 경우 사실혼관계증명 필요(제3자와 혼인관계 없으며, 1년 이상 동거해야 함. 주민등록등본 추가 제출)50% 이상으로 부모와 생계를 달리하는 청년
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : 50.0, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}



  ※ 45세 이하군에 주민등록이 되어있는 18세 ~ 45세 이하의 세대주 청년 또는 혼인신고일 기준 5년 미만인 신혼부부
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}



□ 예산군으로 귀농하고자 하는 20~40대 예비귀농인
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}



□ 부여군 주민등록을 두고 거주하거나 거주 예정인 무주택 청년
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}



□ 대상자 : ⌜청년기본법⌟상 청년(만 19~34세 이하)으로 부모님과 별도 거주하는 무주택자
최소 나이 : 19, 최대 나이 : 34, 지역 : None,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {}


ㅇ기혼자:부부및자녀등포함가구원수계산(최소2인)단독세대를구성하고(예정포함)미혼인경우1인기준적용형제·자매는가구원수에서제외),부모합산소득으로판별(본인소득제외)
최소 나이 : None, 최대 나이 : None, 지역 : None,             소득 제한 : 150.0, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : True,                 부가 조건: {}





# 부가 요건
❍ 지원요건 : 전세사기피해자 결정일 현재
- 무주택자

# 지역

# 나이
- 만19세이상~만39세이하

# 소득
- 연소득(부부합산) 6천만원
- (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하 > 60

# (New) 재산
- 

아 이거 뭘 해야 하나. 너무 자세히 하려고 말아야지. 키워드 몇 개만 잘 되게 하고 ... 
                                


# 보증금 제한
- 임차보증금 5천만원 이하 >> 5로


# 지역
❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
최소 나이 : None, 최대 나이 : None, 지역 : 대전,             소득 제한 : None, 월세 제한 : None,                 보증금 제한 : None, 결혼 유무 : False,                 부가 조건: {전세 사기 피해}



In [30]:
import json
from dataclasses import dataclass
from typing import List, Optional, Dict, Any
import re
from datetime import datetime, date

debug=True

@dataclass
class MonetaryValue:
    amount: int  # 원 단위
    original_text: str

@dataclass
class Period:
    start_date: Optional[date]
    end_date: Optional[date]
    original_text: str

@dataclass
class IncomeRequirement:
    type: str  # "중위소득", "도시근로자" 등
    percentage: Optional[float]  # 비율 (예: 120.0)
    amount: Optional[MonetaryValue]  # 구체적 금액이 명시된 경우
    household_type: str  # "원가구", "청년가구", "부부합산" 등

@dataclass
class PolicyCriteria:
    age_min: Optional[int]
    age_max: Optional[int]
    region: List[str]
    marriage_required: Optional[bool]
    residence_status: Dict[str, Any]
    income_requirements: List[IncomeRequirement]
    asset_limit: Optional[MonetaryValue]
    application_period: Optional[Period]
    support_amount: Optional[MonetaryValue]
    requirements: Dict[str, bool]
    validation_errors: List[str]
    income_assets: Dict[str, Any]
    status: Dict[str, bool]

    def __str__(self):
        return (
            f"PolicyCriteria(\n"
            f"  age_min: {self.age_min},\n"
            f"  age_max: {self.age_max},\n"
            f"  region: {', '.join(self.region) if self.region else 'None'},\n"
            f"  marriage_required: {self.marriage_required},\n"
            f"  residence_status: {self.residence_status},\n"
            f"  income_requirements: {self.income_requirements},\n"
            f"  asset_limit: {self.asset_limit},\n"
            f"  application_period: {self.application_period},\n"
            f"  support_amount: {self.support_amount},\n"
            f"  requirements: {self.requirements},\n"
            f"  validation_errors: {self.validation_errors},\n"
            f"  income_assets: {self.income_assets},\n"
            f"  status: {self.status}\n"
            f")"
        )

class KoreanNumberConverter:
    def __init__(self):
        self.korean_numbers = {
            '일': 1, '이': 2, '삼': 3, '사': 4, '오': 5,
            '육': 6, '칠': 7, '팔': 8, '구': 9,
            '일': 1, '둘': 2, '셋': 3, '넷': 4, '다섯': 5,
            '여섯': 6, '일곱': 7, '여덟': 8, '아홉': 9,
            '십': 10, '백': 100, '천': 1000, '만': 10000,
            '억': 100000000
        }
        
    def convert_to_number(self, korean_text: str) -> Optional[int]:
        try:
            # 숫자로 된 경우 바로 변환
            return int(korean_text)
        except ValueError:
            result = 0
            temp = 0
            unit = 1
            
            for char in korean_text:
                if char in self.korean_numbers:
                    number = self.korean_numbers[char]
                    if number >= 10000:
                        temp = temp if temp > 0 else 1
                        result += (temp * number)
                        temp = 0
                    elif number >= 10:
                        temp = temp if temp > 0 else 1
                        temp *= number
                    else:
                        temp = number
            
            return result + temp

class MonetaryParser:
    def __init__(self):
        self.number_converter = KoreanNumberConverter()
        self.amount_patterns = [
            r'(\d+|\w+)(?:백만|천만|만|억)원',
            r'(\d+|\w+)원',
            r'금?\s*(\d+|\w+)(?:백만|천만|만|억)\s*원?'
        ]
        
    def parse_amount(self, text: str) -> Optional[MonetaryValue]:
        for pattern in self.amount_patterns:
            match = re.search(pattern, text)
            if match:
                amount_text = match.group(1)
                unit_text = match.group(0)
                
                base_amount = self.number_converter.convert_to_number(amount_text)
                if not base_amount:
                    continue
                    
                # 단위 처리
                if '억' in unit_text:
                    amount = base_amount * 100000000
                elif '천만' in unit_text:
                    amount = base_amount * 10000000
                elif '백만' in unit_text:
                    amount = base_amount * 1000000
                elif '만' in unit_text:
                    amount = base_amount * 10000
                else:
                    amount = base_amount
                    
                return MonetaryValue(amount=amount, original_text=match.group(0))
        
        return None

class DateParser:
    def __init__(self):
        self.date_patterns = [
            r'(\d{4})[./\s-](\d{1,2})[./\s-](\d{1,2})',  # 2024-01-01
            r'(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일',    # 2024년 1월 1일
            r'(\d{2})\.(\d{1,2})\.(\d{1,2})',           # 24.1.1
        ]
        self.period_patterns = [
            r'(?:신청|접수|모집)기간\s*:?\s*([^~]*)[~까지]([^\n]*)',
            r'(\d{4}[./년\s]\d{1,2}[./월\s]\d{1,2}[일]?\s*)[~부터\s]+(\d{4}[./년\s]\d{1,2}[./월\s]\d{1,2}[일]?)',
        ]
        
    def parse_date(self, text: str) -> Optional[date]:
        for pattern in self.date_patterns:
            match = re.search(pattern, text)
            if match:
                year = int(match.group(1))
                month = int(match.group(2))
                day = int(match.group(3))
                
                # 2자리 연도 처리
                if year < 100:
                    year += 2000
                    
                try:
                    return date(year, month, day)
                except ValueError:
                    continue
        
        return None
        
    def parse_period(self, text: str) -> Optional[Period]:
        for pattern in self.period_patterns:
            match = re.search(pattern, text)
            if match:
                start_text = match.group(1)
                end_text = match.group(2)
                
                start_date = self.parse_date(start_text)
                end_date = self.parse_date(end_text)
                
                return Period(
                    start_date=start_date,
                    end_date=end_date,
                    original_text=match.group(0)
                )
        
        return None

class IncomeParser:
    def __init__(self):
        self.patterns = {
            "중위소득": r'중위소득\s*(\d+)%\s*(?:이하|미만)?',
            "도시근로자": r'도시근로자\s*(?:월평균\s*)?소득\s*(\d+)%\s*(?:이하|미만)?'
        }
        
    def parse_income_requirements(self, text: str) -> List[IncomeRequirement]:
        requirements = []
        
        for income_type, pattern in self.patterns.items():
            matches = re.finditer(pattern, text)
            for match in matches:
                percentage = float(match.group(1))
                
                # 가구 유형 확인
                household_type = "일반"
                if "원가구" in text:
                    household_type = "원가구"
                elif "부부합산" in text:
                    household_type = "부부합산"
                elif "청년" in text:
                    household_type = "청년가구"
                
                requirements.append(IncomeRequirement(
                    type=income_type,
                    percentage=percentage,
                    amount=None,  # 구체적 금액은 별도 처리 필요
                    household_type=household_type
                ))
                
        return requirements



class RequirementsValidator:
    def validate_requirements(self, req: PolicyCriteria) -> List[str]:
        errors = []
        
        # 나이 검증
        if req.age_min is not None and req.age_max is not None:
            if req.age_min > req.age_max:
                errors.append(f"최소 나이({req.age_min})가 최대 나이({req.age_max})보다 큽니다")
                
        # 날짜 검증
        if req.application_period:
            if (req.application_period.start_date and 
                req.application_period.end_date and 
                req.application_period.start_date > req.application_period.end_date):
                errors.append("시작일이 종료일보다 늦습니다")
                
        # 필수 항목 검증
        if not req.region and not req.requirements.get("전국대상", False):
            errors.append("지역 정보가 없습니다")
            
        return errors


class RegionManager:
    def __init__(self):
        self.region_dict = {
            
"경상북도": [
            "포항시 남구", "포항시 북구", "경주시", "김천시", "안동시", "구미시", "영주시", 
            "영천시", "상주시", "문경시", "경산시", "군위군", "의성군", "청송군", "영양군",
            "영덕군", "청도군", "고령군", "성주군", "칠곡군", "예천군", "봉화군", "울진군",
            "울릉군"
        ],
        "대전광역시": ["동구", "중구", "서구", "유성구", "대덕구"],
        "서울특별시": [
            "종로구", "중구", "용산구", "성동구", "광진구", "동대문구", "중랑구", "성북구",
            "강북구", "도봉구", "노원구", "은평구", "서대문구", "마포구", "양천구", "강서구",
            "구로구", "금천구", "영등포구", "동작구", "관악구", "서초구", "강남구", "송파구",
            "강동구"
        ],
        "부산광역시": [
            "중구", "서구", "동구", "영도구", "부산진구", "동래구", "남구", "북구",
            "해운대구", "사하구", "금정구", "강서구", "연제구", "수영구", "사상구",
            "기장군"
        ],
        "인천광역시": [
            "중구", "동구", "미추홀구", "연수구", "남동구", "부평구", "계양구", "서구",
            "강화군", "옹진군"
        ],
        "광주광역시": ["동구", "서구", "남구", "북구", "광산구"],
        "대구광역시": [
            "중구", "동구", "서구", "남구", "북구", "수성구", "달서구", "달성군"
        ],
        "울산광역시": ["중구", "남구", "동구", "북구", "울주군"],
        "세종특별자치시": ["세종시"],
        "제주특별자치도": ["제주시", "서귀포시"],
        "기타": ["기타"]
        }
        
        # Create reverse lookup dictionary
        self.district_to_region = {}
        for region, districts in self.region_dict.items():
            for district in districts:
                self.district_to_region[district] = region
                # Also add the district name without the 시/군/구
                district_name = re.sub(r'시|군|구$', '', district)
                self.district_to_region[district_name] = region

    def normalize_region(self, region_text: str) -> List[str]:
        """주어진 텍스트에서 지역 정보를 정규화하여 반환"""
        if not region_text:
            return []
            
        found_regions = []
        
        # 광역시/도 직접 매칭
        for region in self.region_dict.keys():
            if region in region_text:
                found_regions.append(region)
                
        # 구/군 매칭
        for district in self.district_to_region.keys():
            if district in region_text:
                parent_region = self.district_to_region[district]
                if parent_region not in found_regions:
                    found_regions.append(parent_region)
                found_regions.append(district)
                
        return found_regions


class ExtendedRequirementsParser():
    def __init__(self):
        self.age_patterns = [
            r'(?:만\s*)?(\d+)\s*[~∼-]\s*(?:만\s*)?(\d+)\s*세?',  # 19-39세, 만 19~39세
            r'(?:만\s*)?(\d+)\s*세?\s*이[상하]',  # 19세 이상, 만 19세 이상
            r'청년\(\s*(?:만\s*)?(\d+)\s*[~∼-]\s*(?:만\s*)?(\d+)\s*세?\s*\)',  # 청년(19-39세)
            r'(?:만\s*)?(\d+)\s*세\s*(?:이상|~)\s*(?:만\s*)?(\d+)\s*세\s*(?:이하|미만)',  # 18세 이상 39세 이하
            r'(?:만\s*)?(\d+)\s*세\s*~\s*(?:만\s*)?(\d+)\s*세',  # 18세 ~ 34세
        ]
        
        self.region_patterns = [
            r'([가-힣]+[시군구도])[에서\s]',  # ~시/군/구/도에서
            r'([가-힣]+[시군구도])[ 거주]',  # ~시/군/구/도 거주
            r'([가-힣]+[시군구도])\s',  # ~시/군/구/도
            r'지역기준[:\s]*([가-힣,\s]+)',
            r'([가-힣]+[시군구도])\s*내',  # 경북도 내
            r'([가-힣]+[시군구도])\s*소재',  # 대전시 소재
        ]
        
        self.income_patterns = [
            r'전년도\s*도시근로자\s*월평균소득의\s*(\d+)%',  # 전년도 도시근로자 월평균소득의 120%
            r'연소득\s*(?:\(부부합산\))?\s*(\d+)(?:천만|백만|억)원\s*이하',  # 연소득(부부합산) 6천만원 이하
            r'소득\s*:\s*(?:\(([^)]+)\))?\s*기준\s*중위소득\s*(\d+)%\s*이하',  # (청년독립가구) 기준 중위소득 60%이하
        ]
        
        # 기존 코드 유지
        self.marriage_patterns = [
            r'신혼부부',
            r'혼인',
            r'결혼',
            r'미혼'
        ]
        self.region_manager = RegionManager()
        self.monetary_parser = MonetaryParser()
        self.date_parser = DateParser()
        self.income_parser = IncomeParser()
        self.validator = RequirementsValidator()

    def _get_detail(self, item: Dict, title: str) -> str:
        for detail in item["Details"]:
            if detail["Title"] == title:
                return detail["Content"]
        return ""


    def extract_age(self, text: str) -> tuple[Optional[int], Optional[int]]:
        for pattern in self.age_patterns:
            match = re.search(pattern, text)
            if match:
                if len(match.groups()) == 2:
                    return int(match.group(1)), int(match.group(2))
                else:
                    age = int(match.group(1))
                    if '이상' in text:
                        return age, None
                    elif '이하' in text or '미만' in text:
                        return None, age
                    elif '대' in text:
                        return age, age + 9
        return None, None


    def extract_regions(self, text: str) -> List[str]:
        found_regions = set()
        
        for pattern in self.region_patterns:
            matches = re.finditer(pattern, text)
            for match in matches:
                region_text = match.group(1).strip()
                # 쉼표로 구분된 여러 지역 처리
                for region in region_text.split(','):
                    region = region.strip()
                    # 지역명이 2글자 이상인 경우에만 처리
                    if len(region) >= 2:
                        normalized_regions = self.region_manager.normalize_region(region)
                        found_regions.update(normalized_regions)
        
        return list(found_regions)

    def extract_marriage_status(self, text: str) -> Optional[bool]:
        if '미혼' in text:
            return False
        elif any(keyword in text for keyword in ['신혼부부', '혼인', '결혼']):
            return True
        return None

    def extract_residence_status(self, text: str) -> Dict[str, Any]:
        status = {
            "무주택": False,
            "전월세": False,
            "임차보증금_제한": None,
            "월세_제한": None
        }
        
        if '무주택' in text:
            status["무주택"] = True
        
        if '전월세' in text or '월세' in text:
            status["전월세"] = True
            
        # 임차보증금 제한 추출
        match = re.search(r'임차보증금\s*(\d+)[만천억]*원', text)
        if match:
            amount = self._convert_korean_amount(match.group(1))
            status["임차보증금_제한"] = amount
            
        # 월세 제한 추출
        match = re.search(r'월세\s*(\d+)[만천]*원', text)
        if match:
            amount = self._convert_korean_amount(match.group(1))
            status["월세_제한"] = amount
            
        return status

    def extract_income_assets(self, text: str) -> Dict[str, Any]:
        income_assets = {
            "소득_기준": [],
            "재산_기준": None,
            "기타_소득조건": []
        }
        
        # 중위소득 기준 추출
        for pattern in self.income_patterns:
            matches = re.finditer(pattern, text)
            for match in matches:
                if '도시근로자' in pattern:
                    income_assets["소득_기준"].append(f"도시근로자 {match.group(1)}%")
                elif '연소득' in pattern:
                    amount = self._convert_korean_amount(match.group(1))
                    income_assets["소득_기준"].append(f"연소득 {amount}만원")
                else:
                    household_type = match.group(1) if match.group(1) else ""
                    percentage = match.group(2)
                    income_assets["소득_기준"].append(f"중위소득 {percentage}% ({household_type})")
            
        # 재산 기준 추출 (기존 코드 유지)
        match = re.search(r'재산\s*(\d+)(?:백만|천만|억)원', text)
        if match:
            income_assets["재산_기준"] = self._convert_korean_amount(match.group(1))
            
        return income_assets

    def _convert_korean_amount(self, amount_str: str) -> int:
        # 숫자 변환 로직 구현
        try:
            return int(amount_str)
        except ValueError:
            return 0

    def extract_status(self, text: str) -> Dict[str, bool]:
        status = {
            "대학생": False,
            "직장인": False,
            "창업자": False,
            "귀농인": False
        }
        
        if '대학생' in text or '재학생' in text:
            status["대학생"] = True
        if '직장' in text or '근로자' in text:
            status["직장인"] = True
        if '창업' in text:
            status["창업자"] = True
        if '귀농' in text:
            status["귀농인"] = True
            
        return status

    def extract_requirements(self, text: str) -> Dict[str, bool]:
        requirements = {
            "청약통장": False,
            "전입신고": False,
            "부모별도거주": False
        }
        
        if '청약통장' in text:
            requirements["청약통장"] = True
        if '전입신고' in text:
            requirements["전입신고"] = True
        if '부모' in text and ('별도' in text or '따로' in text):
            requirements["부모별도거주"] = True
            
        return requirements

    
    def parse(self, item: Dict) -> PolicyCriteria:
        # 기본 정보 추출 (이전 코드의 기능 활용)
        text = self._get_detail(item, "거주지 및 소득")
        age_min, age_max = self.extract_age(text)
        regions = self.extract_regions(text)
        marriage_required = self.extract_marriage_status(text)
        residence_status = self.extract_residence_status(text)
        income_assets = self.extract_income_assets(text)
        status = self.extract_status(text)
        requirementss = self.extract_requirements(text)
        
        # 기타 조건은 향후 확장성을 위해 리스트로 유지
        # other = []
        
        # 새로운 정보 추출
        income_requirements = self.income_parser.parse_income_requirements(text)
        application_period = self.date_parser.parse_period(text)
        
        # 지원금액 추출
        support_amount = None
        if "지원금액" in text or "지원한도" in text:
            amount_text = text[text.find("지원금액"):]
            support_amount = self.monetary_parser.parse_amount(amount_text)
        
        # 요구사항 생성
        requirements = PolicyCriteria(
            age_min=age_min,
            age_max=age_max,
            region=regions,
            marriage_required=marriage_required,
            residence_status=residence_status,  # 이전 코드의 기능 활용
            income_requirements=income_requirements,
            asset_limit=None,  # 자산 제한 추출 필요
            application_period=application_period,
            support_amount=support_amount,
            requirements=requirementss,  # 이전 코드의 기능 활용
            validation_errors=[],
            income_assets=income_assets,
            status=status,
        )
        
        if debug:
            print(text)
            print(requirements)
            print('-'*50)

        # 검증 수행
        requirements.validation_errors = self.validator.validate_requirements(requirements)
        
        return requirements


@dataclass
class Policy:
    policy_id: str
    title: str
    criteria: PolicyCriteria
    description: str
    details: Dict[str, str]

class PolicyFilter:
    def __init__(self, json_data: str):
        self.policies = self._parse_policies(json_data)
    
    def _parse_policies(self, json_data: str) -> List[Policy]:
        data = json.loads(json_data)
        policies = []
        parser = ExtendedRequirementsParser()
        
        for item in data:
            criteria=parser.parse(item)
            
            policy = Policy(
                policy_id=self._get_detail(item, "정책 번호"),
                title=item["Policy Title"],
                criteria=criteria,
                description=item["Description"],
                details={detail["Title"]: detail["Content"] for detail in item["Details"]}
            )
            policies.append(policy)
            
        
        return policies
    
    def _get_detail(self, item: Dict, title: str) -> str:
        for detail in item["Details"]:
            if detail["Title"] == title:
                return detail["Content"]
        return ""
    
    
    def filter_policies(self, 
                       age: int = None,
                       region: str = None,
                       income_percent: float = None,
                       monthly_rent: int = None,
                       deposit: int = None,
                       is_married: bool = None) -> List[Policy]:
        """
        주어진 조건에 맞는 정책들을 필터링하여 반환합니다.
        
        Args:
            age: 나이
            region: 지역
            income_percent: 중위소득 대비 비율 (%)
            monthly_rent: 월세 금액 (만원)
            deposit: 보증금 금액 (만원)
            is_married: 혼인 여부
        """
        eligible_policies = []
        
        for policy in self.policies:
            criteria = policy.criteria
            
            # 각 조건 검사
            if age is not None and criteria.age_min is not None and criteria.age_max is not None:
                if not (criteria.age_min <= age <= criteria.age_max):
                    continue
                    
            # if region is not None and criteria.region is not None:
            #     if criteria.region != region:
            #         continue
                    
            # if income_percent is not None and criteria.income is not None:
            #     if income_percent > criteria.income_limit:
            #         continue
                    
            # if monthly_rent is not None and criteria.monthly_rent_limit is not None:
            #     if monthly_rent > criteria.monthly_rent_limit:
            #         continue
                    
            # if deposit is not None and criteria.deposit_limit is not None:
            #     if deposit > criteria.deposit_limit:
            #         continue
                    
            # if is_married is not None and criteria.marriage_required is not None:
            #     if criteria.marriage_required and not is_married:
            #         continue
            
            eligible_policies.append(policy)
            
        return eligible_policies

def main():
    # 사용 예시
    with open('filtered_policies.json', 'r', encoding='utf-8') as f:
        json_data = f.read()
    
    policy_filter = PolicyFilter(json_data)
    
    # 예시: 28세, 경북 거주, 중위소득 100%, 월세 50만원, 보증금 3000만원, 기혼
    eligible_policies = policy_filter.filter_policies(
        age=28,
        region="경북",
        income_percent=100,
        monthly_rent=50,
        deposit=3000,
        is_married=True
    )

    print(len(eligible_policies))
    
    for policy in eligible_policies:
        print(f"\n정책명: {policy.title}")
        print(f"정책 ID: {policy.policy_id}")
        print(f"지원 내용: {policy.details.get('거주지 및 소득', '')}")

if __name__ == "__main__":
    main()

❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
PolicyCriteria(
  age_min: None,
  age_max: None,
  region: None,
  marriage_required: None,
  residence_status: {'무주택': False, '전월세': False, '임차보증금_제한': None, '월세_제한': None},
  income_requirements: [],
  asset_limit: None,
  application_period: None,
  support_amount: None,
  requirements: {'청약통장': False, '전입신고': False, '부모별도거주': False},
  validation_errors: [],
  income_assets: {'소득_기준': [], '재산_기준': None, '기타_소득조건': []},
  status: {'대학생': False, '직장인': False, '창업자': False, '귀농인': False}
)
--------------------------------------------------
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
PolicyCriteria(
  age_min: 19,
  age_max: None,
  region: 북, 경상북도, 울산광역시,
  marriage_required: True,
  residence_status: {'무주택': True, '전월세': True, '임차보증금_제한': 5, '월세_제한': 80},
  income_requirements: [],
  asset_limit: None,
  application_p

# json에서 원하는 항목만 추출하기 - 3개


In [75]:
import json

def extract_operation_periods(json_data):
    """
    Extracts operation periods from the JSON data structure.
    
    Args:
        json_data (list): List of policy dictionaries
    
    Returns:
        list: List of tuples containing (Policy Title, Operation Period)
    """
    operation_periods = []
    
    for policy in json_data:
        policy_title = policy.get("Policy Title", "제목 없음")
        
        # Search through Details for operation period
        operation_period = None
        temp=None
        for detail in policy.get("Details", []):
            if detail.get("Title") == "주관 기관":
                operation_period = detail.get("Content", "기간 정보 없음")
                break
        for detail in policy.get("Details", []):
            if detail.get("Title") == "거주지 및 소득":
                temp = detail.get("Content", "기간 정보 없음")
                break
                
        operation_periods.append((policy_title, operation_period, temp))
    
    return operation_periods

def main():
    # Load and parse JSON data
    try:
        with open('filtered_policies.json', 'r', encoding='utf-8') as file:
            json_data = json.load(file)
            
        # Extract operation periods
        periods = extract_operation_periods(json_data)
        
        # Print results
        print("\n=== 사업 운영 기간 정보 ===\n")
        for title, period, temp in periods:
            #print(f"정책명: {title}")
            print(f"{period if period else ''}")
            print(f"{temp if temp else ''}")
            
            print("-" * 50)
            
    except FileNotFoundError:
        print("Error: JSON 파일을 찾을 수 없습니다.")
    except json.JSONDecodeError:
        print("Error: JSON 파일 형식이 올바르지 않습니다.")
    except Exception as e:
        print(f"Error: 예상치 못한 오류가 발생했습니다 - {str(e)}")

if __name__ == "__main__":
    main()


=== 사업 운영 기간 정보 ===

대전 전세피해지원센터
❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
--------------------------------------------------
경상북도 건축디자인과
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
--------------------------------------------------
광산구청
-
--------------------------------------------------
인천광역시 청년정책담당관
○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 

# json에서 원하는 항목만 추출하기 - 2개

In [78]:
import json

def extract_operation_periods(json_data):
    """
    Extracts operation periods from the JSON data structure.
    
    Args:
        json_data (list): List of policy dictionaries
    
    Returns:
        list: List of tuples containing (Policy Title, Operation Period)
    """
    operation_periods = []
    
    for policy in json_data:
        policy_title = policy.get("Policy Title", "제목 없음")
        
        # Search through Details for operation period
        operation_period = None
        temp=None
        for detail in policy.get("Details", []):
            if detail.get("Title") == "거주지 및 소득":
                operation_period = detail.get("Content", "기간 정보 없음")
                break
        
        operation_periods.append((policy_title, operation_period))
    
    return operation_periods

def main():
    # Load and parse JSON data
    try:
        with open('filtered_policies.json', 'r', encoding='utf-8') as file:
            json_data = json.load(file)
            
        # Extract operation periods
        periods = extract_operation_periods(json_data)
        
        # Print results
        print("\n=== 사업 운영 기간 정보 ===\n")
        for title, period in periods:
            #print(f"정책명: {title}")
            print(f"{period if period else ''}")
            
            
    except FileNotFoundError:
        print("Error: JSON 파일을 찾을 수 없습니다.")
    except json.JSONDecodeError:
        print("Error: JSON 파일 형식이 올바르지 않습니다.")
    except Exception as e:
        print(f"Error: 예상치 못한 오류가 발생했습니다 - {str(e)}")

if __name__ == "__main__":
    main()


=== 사업 운영 기간 정보 ===

❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
-
○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)
※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
상주시 청년(만 19세 ~ 39세 이하

# 사업 기간 포맷

=== 사업 운영 기간 정보 ===



2024.11.05.~2024.12.27.
2024. 2. ~ 2025. 2.







2024. 2. ~ 2025. 2.
2024. 2. ~ 2025. 2. * 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)



-
-
○ 사업기간 : 2024. 1. ~ 12.
○ 사업기간 : 2022. 1. ~ 2025. 3.
○ 사업기간 : 2020. 12. ~ 2025. 12.
○ 사업기간 : 2024. 1. ~ 2025. 7.
○ 사업기간 : 2023. 5. ~ 2026. 5.
○ 사업기간 : 2023. 5. ~ 2026. 5.
○ 사업기간 : 2023. 5. ~ 2026. 5.
○ 사업기간 : 2023. 5. ~ 2026. 5.
○ 사업기간 : 2023. 5 ~ 2026. 5
○ 사업기간 : 2022. 1. ~ 2025. 11.
○ 사업기간 : 2019. 8. ~ 2024. 1.
○ 사업기간 : 2017. ~ 2026.
○ 사업기간 : 연중
○ 사업기간 : '19. 4. ~ '26. 8.
○ 사업기간 : '17. ~ '26.
○ 기 간 : '23. ~ 계속사업
○ 추진기간 : '24. 1. ~ 12.
○ 사업기간 : '24. 1. ~ 12.
※ 2019년 중구지회 협약에 따른 연장
-


2024.1. ~ 12.
-
-
-
-
-
-
-
-
-




2024.1. ~ 12.
-


-
-
• 사업기간: ’24. 2. ~ ‘26. 12. (※신청기간: ‘24.2.26.부터 1년간)
□ 2024. 1. ~ 예산소진시까지
 □ 지급기간 : 2024. 3월 ~ 2026. 12월5. 2. 25.(화)
□ 2024.1.1.~2024.12.31.
□ 2024-01-01~2024-12-31
□ 2018. 5. ~ 현재
2022-08-22~2026-12-31
-
□ 2024. 1. 22. ~ 2024. 12. 31.
□ 2024. 1. ~ 예산소진시까지
□ 2024.01.01.~2024.12.31.
-

2024-02-26 ~ 2026-12-31

사업기간2024-01-01 ~ 2024-12-31
2024.01.01.~2024.12.31.

2024-01-01~2024-12-31
2024. 2. ~ 2025. 2.

□ 2024. 3. ~ 2026. 12.
2024-03-11~2024-12-20

□ 2024. 3.~2024. 12
□ 2024.01.01.~2024.12.31.

2024.1. ~ 12.

2024. 6. ~ 2024. 12.
2024.1 ~ 2024.12
2024. 1월 ~ 2024. 12월



In [34]:
# 사업 운영 기간 파서
import re

# 날짜 패턴별 정규표현식
date_patterns = {
    # 1. YYYY.MM.DD. ~ YYYY.MM.DD. 형식
    'full_date_dots': r'(\d{4})\.(\d{1,2})\.(\d{1,2})\.?\s*~\s*(\d{4})\.(\d{1,2})\.(\d{1,2})\.?',
    
    # 2. YYYY. MM. ~ YYYY. MM. 형식
    'year_month_dots': r'(\d{4})\.\s*(\d{1,2})\.\s*~\s*(\d{4})\.\s*(\d{1,2})\.',
    
    # 3. YYYY-MM-DD~YYYY-MM-DD 형식
    'full_date_hyphens': r'(\d{4})-(\d{2})-(\d{2})\s*~\s*(\d{4})-(\d{2})-(\d{2})',
    
    # 4. YYYY. M. ~ MM. 형식 (같은 해 다른 달)
    'same_year_months': r'(\d{4})\.\s*(\d{1,2})\.\s*~\s*(\d{1,2})\.',
    
    # 5. 'YY. ~ 'YY. 형식
    'short_years': r'\'(\d{2})\.\s*~\s*\'(\d{2})\.',
    
    # 6. 'YY. MM. ~ 'YY. MM. 형식
    'short_year_month': r'\'(\d{2})\.\s*(\d{1,2})\.\s*~\s*\'(\d{2})\.\s*(\d{1,2})\.',
    
    # 7. YYYY년 MM월 ~ YYYY년 MM월 형식
    'korean_date': r'(\d{4})[년]\s*(\d{1,2})[월]\s*~\s*(\d{4})[년]\s*(\d{1,2})[월]',
    
    # 8. YYYY.M ~ YYYY.MM 형식
    'year_month_minimal': r'(\d{4})\.(\d{1,2})\s*~\s*(\d{4})\.(\d{1,2})',
    
    # 9. [NEW] YYYY. ~ YYYY. 형식 (연도만)
    'years_only': r'(\d{4})\.\s*~\s*(\d{4})\.',
    
    # 10. [NEW] YYYY. MM. DD.(요일) 형식
    'date_with_day': r'(\d{4})\.\s*(\d{1,2})\.\s*(\d{1,2})\.\s*\([월화수목금토일]\)',
    
    # 11. [NEW] 특수 케이스 패턴
    'special_cases': r'(연중|예산소진시까지|계속사업|현재)'
}

def parse_date_string(date_str):
    """
    주어진 날짜 문자열에서 시작일과 종료일을 추출
    
    Args:
        date_str (str): 날짜 문자열
    
    Returns:
        dict: 파싱된 날짜 정보 또는 특수 케이스 문자열
    """
    # 특수 케이스 먼저 체크
    special_match = re.search(date_patterns['special_cases'], date_str)
    if special_match:
        return {'type': 'special_case', 'value': special_match.group(1)}
    
    for pattern_name, pattern in date_patterns.items():
        if pattern_name == 'special_cases':
            continue
            
        match = re.search(pattern, date_str)
        if match:
            groups = match.groups()
            
            # 패턴별 결과 처리
            if pattern_name == 'full_date_dots':
                return {
                    'type': 'full_date',
                    'start': {'year': groups[0], 'month': groups[1], 'day': groups[2]},
                    'end': {'year': groups[3], 'month': groups[4], 'day': groups[5]}
                }
            elif pattern_name in ['year_month_dots', 'korean_date', 'year_month_minimal']:
                return {
                    'type': 'year_month',
                    'start': {'year': groups[0], 'month': groups[1]},
                    'end': {'year': groups[2], 'month': groups[3]}
                }
            elif pattern_name == 'full_date_hyphens':
                return {
                    'type': 'full_date',
                    'start': {'year': groups[0], 'month': groups[1], 'day': groups[2]},
                    'end': {'year': groups[3], 'month': groups[4], 'day': groups[5]}
                }
            elif pattern_name == 'same_year_months':
                return {
                    'type': 'same_year_months',
                    'start': {'year': groups[0], 'month': groups[1]},
                    'end': {'year': groups[0], 'month': groups[2]}
                }
            elif pattern_name == 'short_years':
                start_year = '20' + groups[0]
                end_year = '20' + groups[1]
                return {
                    'type': 'years_only',
                    'start': {'year': start_year},
                    'end': {'year': end_year}
                }
            elif pattern_name == 'short_year_month':
                start_year = '20' + groups[0]
                end_year = '20' + groups[2]
                return {
                    'type': 'year_month',
                    'start': {'year': start_year, 'month': groups[1]},
                    'end': {'year': end_year, 'month': groups[3]}
                }
            elif pattern_name == 'years_only':
                return {
                    'type': 'years_only',
                    'start': {'year': groups[0]},
                    'end': {'year': groups[1]}
                }
            elif pattern_name == 'date_with_day':
                return {
                    'type': 'single_date_with_day',
                    'date': {'year': groups[0], 'month': groups[1], 'day': groups[2]}
                }
    
    return None

# 테스트
test_dates = [
    "2024.11.05.~2024.12.27.",
    "2024. 2. ~ 2025. 2.",
    "2024-01-01~2024-12-31",
    "2024.1. ~ 12.",
    "'19. 4. ~ '26. 8.",
    "2024년 1월 ~ 2024년 12월",
    "2024.1 ~ 2024.12",
    "2017. ~ 2026.",
    "연중",
    "예산소진시까지",
    "2024. 2. 25.(화)"
]

for date in test_dates:
    result = parse_date_string(date)
    if result:
        print(f"\n입력: {date}")
        print(f"결과: {result}")

In [38]:
import re

def parse_operating_periods(text):
    # Regular expression to match date ranges
    date_range_pattern = r"(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일\s*~\s*(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일"
    # Non-date cases like '상시' and '미정'
    status_pattern = r"상시|미정"

    results = []

    for line in text.splitlines():
        # Check for date ranges
        date_match = re.search(date_range_pattern, line)
        if date_match:
            start_year, start_month, start_day, end_year, end_month, end_day = date_match.groups()
            results.append({
                "start_date": f"{start_year}-{int(start_month):02d}-{int(start_day):02d}",
                "end_date": f"{end_year}-{int(end_month):02d}-{int(end_day):02d}"
            })
        else:
            # Check for '상시' or '미정'
            status_match = re.search(status_pattern, line)
            if status_match:
                results.append({
                    "start_date": "0000-0-0",
                    "end_date": "9999-99-99"
                })

    return results

# Example input text
text = """상시
2024년 11월  18일 ~ 2024년 12월  31일
미정
2024년 02월  26일 ~ 2025년 02월  25일
"""

# Parse and print the results
parsed_data = parse_operating_periods(text)
for entry in parsed_data:
    print(entry)



{'start_date': '0000-0-0', 'end_date': '9999-99-99'}
{'start_date': '2024-11-18', 'end_date': '2024-12-31'}
{'start_date': '0000-0-0', 'end_date': '9999-99-99'}
{'start_date': '2024-02-26', 'end_date': '2025-02-25'}


In [40]:
# 나이 추출
import re

def extract_age_range(text):
    # 정규 표현식 정의
    age_pattern = r"(?:(?:만\s*)?(\d+)\s*세\s*~\s*(\d+)\s*세|(?:만\s*)?(\d+)\s*세\s*~\s*제한 없음|(?:만\s*)?제한 없음)"
    match = re.search(age_pattern, text)

    if match:
        if match.group(1) and match.group(2):  # "만 19세 ~ 34세" 형태
            min_age = int(match.group(1))
            max_age = int(match.group(2))
        elif match.group(3):  # "만 19세 ~ 제한 없음" 형태
            min_age = int(match.group(3))
            max_age = 9999
        else:  # "제한 없음" 형태
            min_age = 0
            max_age = 9999
    else:
        # 매치되지 않을 경우 기본 값
        min_age = 0
        max_age = 0

    return min_age, max_age

# 테스트
examples = [
    "만 19세 ~ 34세",
    "만 25세 ~ 제한 없음",
    "제한 없음",
    "만 18세 ~ 만 30세"
]

for example in examples:
    print(f"{example}: {extract_age_range(example)}")


만 19세 ~ 34세: (19, 34)
만 25세 ~ 제한 없음: (25, 9999)
제한 없음: (0, 9999)
만 18세 ~ 만 30세: (0, 0)


In [73]:
# 주관 기관
# 지역 Dictionary
from collections import defaultdict
regions = {
    ("서울"): ["종로", "중구", "용산", "성동", "광진", "동대문", "중랑", "성북", 
             "강북", "도봉", "노원", "은평", "서대문", "마포", "양천", "강서", 
             "구로", "금천", "영등포", "동작", "관악", "서초", "강남", "송파", "강동"],
    ("부산"): ["중구", "서구", "동구", "영도", "부산진", "동래", "남구", "북구", "해운대", 
             "사하", "금정", "강서", "연제", "수영", "사상", "기장"],
    ("대구"): ["중구", "동구", "서구", "남구", "북구", "수성", "달서", "달성"],
    ("인천"): ["중구", "동구", "미추홀", "연수", "남동", "부평", "계양", "서구", "강화", "옹진"],
    ("광주"): ["동구", "서구", "남구", "북구", "광산"],
    ("대전"): ["동구", "중구", "서구", "유성", "대덕"],
    ("울산"): ["중구", "남구", "동구", "북구", "울주"],
    ("세종"): ["세종"],
    ("경기"): ["수원", "성남", "안양", "안산", "용인", "부천", "광명", "평택", 
             "과천", "오산", "시흥", "군포", "의왕", "하남", "이천", "안성", 
             "김포", "화성", "광주", "양주", "포천", "여주", "연천", "가평", "양평"],
    ("강원"): ["춘천", "원주", "강릉", "동해", "태백", "속초", "삼척", 
             "홍천", "횡성", "영월", "평창", "정선", "철원", "화천", "양구", "인제", "고성", "양양"],
    ("충북", "충청북도"): ["청주", "충주", "제천", "보은", "옥천", "영동", "증평", "진천", "괴산", "음성", "단양"],
    ("충남", "충청남도"): ["천안", "공주", "보령", "아산", "서산", "논산", "계룡", "당진", 
             "금산", "부여", "서천", "청양", "홍성", "예산", "태안"],
    ("전북", "전라북도"): ["전주", "군산", "익산", "정읍", "남원", "김제", 
             "완주", "진안", "무주", "장수", "임실", "순창", "고창", "부안"],
    ("전남", "전라남도"): ["목포", "여수", "순천", "나주", "광양", 
             "담양", "곡성", "구례", "고흥", "보성", "화순", "장흥", "강진", "해남", 
             "영암", "무안", "함평", "영광", "장성", "완도", "진도", "신안"],
    ("경북", "경상북도"): ["포항", "경주", "김천", "안동", "구미", "영주", "영천", "상주", 
             "문경", "경산", "군위", "의성", "청송", "영양", "영덕", "청도", 
             "고령", "성주", "칠곡", "예천", "봉화", "울진", "울릉"],
    ("경남", "경상남도"): ["창원", "진주", "통영", "사천", "김해", "밀양", "거제", "양산", 
             "의령", "함안", "창녕", "고성", "남해", "하동", "산청", "함양", "거창", "합천"],
    ("제주"): ["제주", "서귀포"]
}

# 입력 데이터
entries = [
    "서울 강남구청", "경남 창원시", "전남 목포시", "충북 청주시", "세종시", "경기 수원시"
]

# 지역 축약명 처리 함수
def normalize_region_name(name):
    # 도/광역시/특별시 축약형 변환
    mapping = {
        "서울특별시": "서울", "부산광역시": "부산", "대구광역시": "대구",
        "인천광역시": "인천", "광주광역시": "광주", "대전광역시": "대전",
        "울산광역시": "울산", "세종특별자치시": "세종", 
        "경기도": "경기", "강원도": "강원", "충청북도": "충북", "충청남도": "충남",
        "전라북도": "전북", "전라남도": "전남", "경상북도": "경북", "경상남도": "경남",
        "제주특별자치도": "제주"
    }
    return mapping.get(name, name)

# 지역 분류 함수
def classify_regions(entries, regions):
    result = defaultdict(list)

    for entry in entries:
        matched = False
        for regionss in regions.keys():
            if type(regionss)==tuple:
                for region in regionss:
                    if region in entry:
                        result[regionss[0]].append(entry)
                        matched=True
                        break
                if matched:
                    break
            else:
                if regionss in entry:
                    result[regionss].append(entry)
                    matched=True
                    break
        if not matched:
            for region, subregions in regions.items():
                if any(subregion in entry for subregion in subregions):
                    result[region].append(entry)
                    matched = True
                    break
        if not matched:
            result["전국"].append(entry)

    return result




# 입력 데이터
entries = [
    "대전 전세피해지원센터", "경상북도 건축디자인과", "광산구청", "인천광역시 청년정책담당관", 
    "부산시", "상주시청 미래정책실", "국토교통부", "의성군 기획예산담당관 인구정책", 
    "대전전세피해지원센터", "국토교통부", "고흥군청", "인천광역시 청년정책담당관", 
    "국토교통부 민간임대정책과", "금천구청 일자리청년과", "금천구청 일자리청년과 청년동행팀", 
    "전북특별자치도", "-", "울산광역시 건축정책과 주거지원팀(052-229-4415)", 
    "울산도시공사 주택사업팀(052-219-8457)", "울산광역시 북구 노인장애인과 생활보장팀(052-241-7623)", 
    "울산광역시 북구 건축정책과 주택허가팀(052-214-8022)", 
    "울산광역시 동구 건축주택과 주택허가팀(052-209-3792)", 
    "울산광역시 동구 노인장애인과 생활보장팀(052-209-3453)", 
    "욿산광역시 동구 일자리정책과 청년정책팀(052-209-3486)", 
    "울산광역시 중구청 민원지적과(052-290-3485)", "남원시", "광산구청 여성아동과", 
    "도봉구청 청년미래과", "인천광역시 주택정책과", 
    "울산광역시청 건축정책과 주거복지담당 (☏ 052-229-4415)", 
    "울산광역시 울주군 여성가족과 여성가족팀(052-204-1014)", "국토교통부 (민원 콜센터 : 1600-0777)", 
    "울산광역시 북구 건축주택과(052-241-8029)", 
    "김해시청 공동주택과 저소득주거지원팀(☎ 055-330-4318)", "제주특별자치도 / 경제일자리과",
    "제주특별자치도 / 주택토지과(주거복지팀)", "제주특별자치도 / 주거복지팀", "제주특별자치도", 
    "국토교통부", "□ 사하구청 일자리복지과", "□ 문의전화 : 성남시 여성가족과(☎031-729-8547)", 
    "○ 경기도 수원시청 도시재생과 주거복지팀(☎031-228-3028)", "전략주택공급과", "주택정책과", 
    "세종시청", "□ 예산군", "□ 국토교통부", "□ 예산군 농업기술센터", "□ 청양군", 
    "□ 부여시청", "국토교통부", "통영시청 기획예산실 인구청년정책팀 ☎055-650-3162", 
    "□ 청년정책관", "□ 예산군 총무과", "□ 인구가족과", "국토교통부", 
    "제주특별자치도 / 주택토지과(주거복지팀)", "국토교통부", 
    "제주특별자치도 / 주택토지과(주택정책팀)", "국토교통부", 
    "광주광역시 동구청 청년체육과", "서울시청 여성가족정책실- 1인가구담당관", "상주시", 
    "인천광역시 청년정책담당관", "□ 국토교통부", "고령군", "경기도 용인시", 
    "□ 아산시", "□ 보령시청", "서울시 주택정책과", "서울시청 전략주택공급과", 
    "경기도 성남시", "전북특별자치도 청년정책과", "진안군 농촌활력과 청장년지원팀", 
    "정읍시", "완주군", "광주시 청년지원센터(☎ 031-8027-0371)", 
    "인천광역시 연수구 공간정보과", "-", "충주시 기획예산과 청년인구정책팀", 
    "충청북도 과학인재국 RISE추진과 지산학협력팀", 
    "충청북도기획관리실 인구청년정책담당관 청년지원팀", "광주광역시 도시공간국 주택정책과", 
    "대한적십자사", "국토교통부 주택기금과"
]

# 실행
classified_data = classify_regions(entries, regions)
for region, items in classified_data.items():
    print(f"{region}: {len(items)}")
    for item in items:
        print(f"  - {item}")


대전: 2
  - 대전 전세피해지원센터
  - 대전전세피해지원센터
경북: 1
  - 경상북도 건축디자인과
광주: 5
  - 광산구청
  - 광산구청 여성아동과
  - 광주광역시 동구청 청년체육과
  - 광주시 청년지원센터(☎ 031-8027-0371)
  - 광주광역시 도시공간국 주택정책과
인천: 5
  - 인천광역시 청년정책담당관
  - 인천광역시 청년정책담당관
  - 인천광역시 주택정책과
  - 인천광역시 청년정책담당관
  - 인천광역시 연수구 공간정보과
부산: 3
  - 부산시
  - 욿산광역시 동구 일자리정책과 청년정책팀(052-209-3486)
  - □ 사하구청 일자리복지과
('경북', '경상북도'): 3
  - 상주시청 미래정책실
  - 상주시
  - 고령군
전국: 19
  - 국토교통부
  - 국토교통부
  - 국토교통부 민간임대정책과
  - -
  - 국토교통부 (민원 콜센터 : 1600-0777)
  - 국토교통부
  - 전략주택공급과
  - 주택정책과
  - □ 국토교통부
  - 국토교통부
  - □ 청년정책관
  - □ 인구가족과
  - 국토교통부
  - 국토교통부
  - 국토교통부
  - □ 국토교통부
  - -
  - 대한적십자사
  - 국토교통부 주택기금과
('충남', '충청남도'): 9
  - 의성군 기획예산담당관 인구정책
  - □ 예산군
  - □ 예산군 농업기술센터
  - □ 청양군
  - □ 부여시청
  - 통영시청 기획예산실 인구청년정책팀 ☎055-650-3162
  - □ 예산군 총무과
  - □ 아산시
  - □ 보령시청
('전남', '전라남도'): 1
  - 고흥군청
서울: 6
  - 금천구청 일자리청년과
  - 금천구청 일자리청년과 청년동행팀
  - 도봉구청 청년미래과
  - 서울시청 여성가족정책실- 1인가구담당관
  - 서울시 주택정책과
  - 서울시청 전략주택공급과
전북: 2
  - 전북특별자치도
  - 전북특별자치도 청년정책과
울산: 10
  - 울산광역시 건축정책과 주거지원팀(052-229-4415)
  - 

In [79]:
# 주관 기관
# 지역 Dictionary
from collections import defaultdict
regions = {
    ("서울"): ["종로", "중구", "용산", "성동", "광진", "동대문", "중랑", "성북", 
             "강북", "도봉", "노원", "은평", "서대문", "마포", "양천", "강서", 
             "구로", "금천", "영등포", "동작", "관악", "서초", "강남", "송파", "강동"],
    ("부산"): ["중구", "서구", "동구", "영도", "부산진", "동래", "남구", "북구", "해운대", 
             "사하", "금정", "강서", "연제", "수영", "사상", "기장"],
    ("대구"): ["중구", "동구", "서구", "남구", "북구", "수성", "달서", "달성"],
    ("인천"): ["중구", "동구", "미추홀", "연수", "남동", "부평", "계양", "서구", "강화", "옹진"],
    ("광주"): ["동구", "서구", "남구", "북구", "광산"],
    ("대전"): ["동구", "중구", "서구", "유성", "대덕"],
    ("울산"): ["중구", "남구", "동구", "북구", "울주"],
    ("세종"): ["세종"],
    ("경기"): ["수원", "성남", "안양", "안산", "용인", "부천", "광명", "평택", 
             "과천", "오산", "시흥", "군포", "의왕", "하남", "이천", "안성", 
             "김포", "화성", "광주", "양주", "포천", "여주", "연천", "가평", "양평"],
    ("강원"): ["춘천", "원주", "강릉", "동해", "태백", "속초", "삼척", 
             "홍천", "횡성", "영월", "평창", "정선", "철원", "화천", "양구", "인제", "고성", "양양"],
    ("충북", "충청북도"): ["청주", "충주", "제천", "보은", "옥천", "영동", "증평", "진천", "괴산", "음성", "단양"],
    ("충남", "충청남도"): ["천안", "공주", "보령", "아산", "서산", "논산", "계룡", "당진", 
             "금산", "부여", "서천", "청양", "홍성", "예산", "태안"],
    ("전북", "전라북도"): ["전주", "군산", "익산", "정읍", "남원", "김제", 
             "완주", "진안", "무주", "장수", "임실", "순창", "고창", "부안"],
    ("전남", "전라남도"): ["목포", "여수", "순천", "나주", "광양", 
             "담양", "곡성", "구례", "고흥", "보성", "화순", "장흥", "강진", "해남", 
             "영암", "무안", "함평", "영광", "장성", "완도", "진도", "신안"],
    ("경북", "경상북도"): ["포항", "경주", "김천", "안동", "구미", "영주", "영천", "상주", 
             "문경", "경산", "군위", "의성", "청송", "영양", "영덕", "청도", 
             "고령", "성주", "칠곡", "예천", "봉화", "울진", "울릉"],
    ("경남", "경상남도"): ["창원", "진주", "통영", "사천", "김해", "밀양", "거제", "양산", 
             "의령", "함안", "창녕", "고성", "남해", "하동", "산청", "함양", "거창", "합천"],
    ("제주"): ["제주", "서귀포"]
}

# 입력 데이터
entries = [
    "서울 강남구청", "경남 창원시", "전남 목포시", "충북 청주시", "세종시", "경기 수원시"
]

# 지역 축약명 처리 함수
def normalize_region_name(name):
    # 도/광역시/특별시 축약형 변환
    mapping = {
        "서울특별시": "서울", "부산광역시": "부산", "대구광역시": "대구",
        "인천광역시": "인천", "광주광역시": "광주", "대전광역시": "대전",
        "울산광역시": "울산", "세종특별자치시": "세종", 
        "경기도": "경기", "강원도": "강원", "충청북도": "충북", "충청남도": "충남",
        "전라북도": "전북", "전라남도": "전남", "경상북도": "경북", "경상남도": "경남",
        "제주특별자치도": "제주"
    }
    return mapping.get(name, name)

# 지역 분류 함수
def classify_regions(entries, regions):
    result = defaultdict(list)

    for entry in entries:
        matched = False
        for regionss in regions.keys():
            if type(regionss)==tuple:
                for region in regionss:
                    if region in entry:
                        result[regionss[0]].append(entry)
                        matched=True
                        break
                if matched:
                    break
            else:
                if regionss in entry:
                    result[regionss].append(entry)
                    matched=True
                    break
        if not matched:
            for region, subregions in regions.items():
                if any(subregion in entry for subregion in subregions):
                    result[region].append(entry)
                    matched = True
                    break
        if not matched:
            result["전국"].append(entry)

    return result




# 입력 데이터
entries = """

=== 사업 운영 기간 정보 ===

❍ 지원요건 : 전세사기피해자 결정일 현재 ① 임대차계약을 체결한 피해주택의 소재지가 대전시이고, ② 대전시에 주민등록을 두고 거주하는 자
｢경상북도 청년 기본조례｣상 청년 신혼부부*(만19세이상~만39세이하)가 월세 주택**에 주민등록상 같이 전입신고 되어 있고, 경북도 내 임차보증금 5천만원 이하면서 월세 80만원 이하에 거주하는 연소득(부부합산) 6천만원 이하인 무주택자
-
○ 거주지 : 제한없음○ 소득 : ◎ 청약통장 가입 필수(종류무관) ◎ 소득 : (청년독립가구) 기준 중위소득 60%이하 (원가구) 기준 중위소득 100% 이하◎ 재산 : (청년독립가구) 재산 122백만원 이하 (원가구) 재산 470백만원 이하◎ 주택 : 전입신고 필수 ※ 월세 임차보증금 5천만원 및 월세 70만원 이하 요건 폐지(2024.4.12.~시행)] ※ 제출된 신청서를 토대로 공적자료 조회(조사시점 기준 적용)<가구구성 방법> (청년독립가구) 청년 + 배우자 + 직계비속 + 동일 주소지에 거주하는 그 외 「민법」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)
※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
상주시 청년(만 19세 ~ 39세 이하)이고, 지역 정착 창업사업 참여자
○ (원가구) 청년독립가구 + 1촌이내 직계혈족(부·모)소지에 거주하는 그 외「민법」상 가족소득 50% 이상으로 생계를 달리한다고 시·군·구청장이 인정하는 경우 등은 원가구 소득 미고려
· 지원대상: 신청일 기준, 남편 또는 아내가 1년 이상 의성군에 주소를 두고 거주하며, 혼인신고일 이후 부부가 함께 의성군에 주민등록을 둔 결혼 1년 이하 무주택 신혼부부
- 법령에서 정한 정기점검 기간이 이미 경과하였거나 점검유예한 주택 
※ 보장기관이 인정하는 경우 예외 가능주민등록상 시·군을 달리하는 경우 인정미만의 미혼자녀
 ○ 소득이 없을 경우 국세청 사실증명원 등 소득이 없다는 증빙서류 필요0% 이하
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
 * 19~34세 : 국토부(전국) 청년월세 한시특별 지원 / 35~39세 : 인천형 청년월세 지원의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)」상 가족* (원가구) 청년독립가구 + 1촌 이내 직계혈족(부,모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인(이혼) ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
*입주자 모집공고 확인
공고문 필히 참고
추후 공고문 참고
○ 이주주택 임대차 계약서 상 임차인은 본 사업 신청인과 동일인일 것민등록을 두고 실제 거주하는 자
※ [필독] 기본적으로 전년도 소득증빙자료로 선정여부를 결정하나, 금년도 은행 대출시에도 연령·소득요건은 반드시 유지해야 함
○ 지원대상 : 주거급여 수급가구 내 만 19세 이상 30세 미만 미혼자녀
-
-
-
-
-
-
-
-
-
-
-
-
-
-
○ 대 상 : 18세 이상 39세 이하 무주택 청년노동자
○ 지원대상 : 주거급여 수급자의 19세 ~ 30세 미만의 미혼자녀
○ 대 상 : 동구 거주 또는 생활 청년(18세 ~ 39세)
○ 지원대상 : 중구에 거주·생활 또는 전입예정인 18세 ~ 34세 이하 청년
❍(주택소유여부) 가족관계증명서의 본인 및 배우자 소유 주택이 없을 것지원 불가인)31. 출생자)
※ 아파트, 자가 거주자, 기 지원자 제외
② 2022~2023년 청년 1인 가구 생활안전키트를 지원받지 아니한 사람
○ 대상 : 19세 이상 39세 이하 무주택 미혼 청년19세이상 39세이하)
④ (제외) 주거급여수급자, 울주군 신혼부부 주거지원 사업 대상자와 중복 지급불가전세임대 거주하고 있는 가구①~④요건 모두 만족) 
- 부부합산소득이 기준중위소득 200%(7,365천원) 이하인 가구(2인 기준) 중인 신혼부부
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는 시설, 임차보증금과 월세 제한 없음
○ 주택 : 임대차계약 보증금이 3억원 이하인 주민등록 주소지와 일치하는 주거용 주택증금반환보증에 가입된 경우 신청 가능 (2024. 6. 30. 이전 신청자에 한함.)
□ 신청대상 : 입주자 모집 공고일(2024. 5. 30.) 현재 만19세 이상 만39세 이하의 청년으로 전년도 도시근로자 월평균소득의 120% (4,179,557원)이하인 자


지역기준: 제주도, 제주시, 서귀포시
  ○ 19세∼39세(무주택 저소득 청년)·신혼부부·고령자 등
*보증기관: 주택도시보증공사(HUG), 한국주택금융공사(HF), 서울보증보험(SGI)시 거주 무주택자(본인 및 배우자 모두 무주택자) 
□ 19-34세 부모님과 별도로 거주하는 무주택 청년
※ 제외대상 : 아파트 및 오피스텔 거주자, 자가 소유자자모자)가정
▶ 아동복지시설 :  아동양육시설, 공동생활가정, 가정위탁택자로서 아동복지시설을 만기 또는 중도 퇴소(예정)한 29세 이하 청년
-
※ 2024년 3월 1일 이후 접수자부터 아래의 신청자격 기준 적용및 자산 기준을 충족하는 자
* 사실혼인 경우 사실혼관계증명 필요(제3자와 혼인관계 없으며, 1년 이상 동거해야 함. 주민등록등본 추가 제출)50% 이상으로 부모와 생계를 달리하는 청년
  ※ 45세 이하군에 주민등록이 되어있는 18세 ~ 45세 이하의 세대주 청년 또는 혼인신고일 기준 5년 미만인 신혼부부
  ※ 원가구 : 청년가구+1촌이내 직계혈족(부모)소지 거주중 민법상 가족이하
□ 예산군으로 귀농하고자 하는 20~40대 예비귀농인
□ 다른 시‧군‧구에서 전입일을 기준으로 1년이상 주소를 두고 있다가 군 내에 전입한 자
□ 부여군 주민등록을 두고 거주하거나 거주 예정인 무주택 청년
□ 대상자 : ⌜청년기본법⌟상 청년(만 19~34세 이하)으로 부모님과 별도 거주하는 무주택자
(※ 자세한 사항 공고문 참고)있지 않거나 주거기본법 제17조 최저주거기준의 주거면적에 미달하는 주택을 소유하고 있는 자를 말함
ㅇ기혼자:부부및자녀등포함가구원수계산(최소2인)단독세대를구성하고(예정포함)미혼인경우1인기준적용형제·자매는가구원수에서제외),부모합산소득으로판별(본인소득제외)
-건강보험증(사본) *건강보험 자격확인(통보)서 대체 가능
 ※ 18~39세 또는 직장을 두거나, 활동·생활하고자 하는 무주택 청년
○ (원가구) 기준중위소득 100%이하&(청년독립가구) 기준 중위소득 60%이하무주택 청년(청약저축 가입자)

❍ 지원자격 : 청년가구 소득 기준 중위소득 60% 이하, 원가구 소득 기준 중위소득 100% 이하
지역기준 : 제주도, 제주시, 서귀포시
지역기준 : 제주도, 제주시, 서귀포시
-
서울시 거주 또는 거주예정인 1인가구
-
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
○ 대상 : 인천 19~39세 이하 부모님과 별도 거주 무주택 청년 - 월세지원 신청연령은 신청년도의 출생년을 기준(19~39세가 되는 해의 1.1.~12.31.)* 신청기간 : 2024. 2. 26. ~ 2025. 2. 25.(1년간)모) * (가족의 범위, 민법§779) ❶배우자, 직계혈족 및 형제자매, ❷직계혈족의 배우자, 배우자의 직계혈족 및 배우자의 형제자매(생계를 같이하는 경우에 한함)※ 원가구(부모님) 소득·재산 미고려 : ①30세 이상 ②혼인 ③미혼부·모 ④30세 미만 미혼 청년의 소득이 중위 50% 이상으로 생계를 달리한다고 군수·구청장이 인정하는 경우
 ※ 거주하는 본인 또는 시민 자녀
-

□ 부모와 별도 거주하는 무주택 저소득 청년
□ 가구소득인정액이 기준중위소득 180%이하인 자전원 무주택자 주택구입자금 또는 전월세보증금 대출 후 1개월 이내 전입 예정자
  - 건축물대장상 주택이 아닌 곳과 불법건축물, 다중 주택, 공공임대주택은 지원 불가월세 70만원 이하의 전월세계약하인 자
   - 신혼부부 : 신혼부부 및 자녀 합산 자산 기준 3억 4,500만원 이하수별 가구당 월평균 소득 120%이하(2인가구:6,498,854원 / 3인가구:8.638.379원)
기타 자세한 모집요강 및 세부 내용은 첨부된 공고문 참고
□ 월세가 70만원이 초과되더라도 보증금의 월세환산액(연 5.5%)과 월세액의 합계액이 90만원 이하의 경우는 지원
※ (신청일 기준) 임대차 계약을 맺은 건물(진안군 소재)에 주민등록이 등재되어 있어야 함.세(70만원 이하) 또는 전세(임차보증금 1억 5천만원 이하이면서 대출금 유) 건물
□ 미혼청년(만18 ∼ 39세) 혼인 7년이내/혼인신고일 기준)
    - 기준중위소득 180퍼센트 이하인 본인 (배우자,자녀포함) 소유의 주택이 없는 다자녀가구
※ 이사비 지원액 예산 초과 시, 접수 완료 순으로 선착순 지급를 요청할 수 있음건강보험료 소득판정’기준표상 기준 중위소득 180% 이하
연수구 청년 누구나
□ 소득기준 : (원가구) 기준 중위소득 100% 이하 & (청년독립가구) 기준 중위소득 60% 이하
주거 자금(구입, 전세) 목적으로 금융권 대출을 실행한 충주시 거주 혼인 7년 이내 청년 신혼부부 - 지원대상 세부 자격 공고문 확인
본인 또는 친권자(후견자)의 주소가 충청북도인 자 - (서/동서울관) 수도권 지역 대학의 신입생 또는 재학생 - (청 주 관) 도내 대학(원)의 신입생 또는 재학생
도내 거주 19세 ~ 34세 이하 부모님과 별도거주 무주택 청년 (청약통장 가입 필수) - 소득요건 : 원가구 중위소득 100%이하+청년가구 중위소득 60%이하
-
퇴소했거나 재원중이거나 보호가 종료된 아동(만18세~34세) 1,000명
 (일반형) 부부합산 연소득 5천만원 이하자 중 우대형에 해당하지 아니한 자로 인정되는 자 포함)인 자주(세대주로 인정되는자 포함)인 자불가능중 소득 3분위 전체가구 평균값 이하(십만원 단위에서 반올림)인 자


""".split('\n')

# 실행
classified_data = classify_regions(entries, regions)
for region, items in classified_data.items():
    print(f"{region}: {len(items)}")
    for item in items:
        print(f"  - {item}")


전국: 75
  - 
  - 
  - === 사업 운영 기간 정보 ===
  - 
  - -
  - ※ 아파트를 제외한 주택유형의 경우 임대인이 신청일 기준 해당 주택 소유기간 3개월 미만인 경우, 보증신청 불가 등 협약은행 내규에 따라 협약은행에서 추가 심사 실시
  - ○ (원가구) 청년독립가구 + 1촌이내 직계혈족(부·모)소지에 거주하는 그 외「민법」상 가족소득 50% 이상으로 생계를 달리한다고 시·군·구청장이 인정하는 경우 등은 원가구 소득 미고려
  - - 법령에서 정한 정기점검 기간이 이미 경과하였거나 점검유예한 주택 
  - ※ 보장기관이 인정하는 경우 예외 가능주민등록상 시·군을 달리하는 경우 인정미만의 미혼자녀
  -  ○ 소득이 없을 경우 국세청 사실증명원 등 소득이 없다는 증빙서류 필요0% 이하
  - *입주자 모집공고 확인
  - 공고문 필히 참고
  - 추후 공고문 참고
  - ○ 이주주택 임대차 계약서 상 임차인은 본 사업 신청인과 동일인일 것민등록을 두고 실제 거주하는 자
  - ※ [필독] 기본적으로 전년도 소득증빙자료로 선정여부를 결정하나, 금년도 은행 대출시에도 연령·소득요건은 반드시 유지해야 함
  - ○ 지원대상 : 주거급여 수급가구 내 만 19세 이상 30세 미만 미혼자녀
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - -
  - ○ 지원대상 : 주거급여 수급자의 19세 ~ 30세 미만의 미혼자녀
  - ❍(주택소유여부) 가족관계증명서의 본인 및 배우자 소유 주택이 없을 것지원 불가인)31. 출생자)
  - ※ 아파트, 자가 거주자, 기 지원자 제외
  - ② 2022~2023년 청년 1인 가구 생활안전키트를 지원받지 아니한 사람
  - - 부부합산소득이 기준중위소득 200%(7,365천원) 이하인 가구(2인 기준) 중인 신혼부부
  - ** 준주택 : 기숙사, 고시원, 오피스텔 등다세대주택 등”, 그 외 거주를 목적으로 하는